
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/first?currentSchema=second
    username: second
    password: second
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 8181
